name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      GOFLAGS: -mod=readonly

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Please
        uses: sagikazarmark/setup-please-action@v0
        with:
          save-logs: 'true'
        env:
          # See https://github.com/sagikazarmark/setup-please-action/issues/6
          MATRIX_CONTEXT: ${{ toJson(matrix) }}

      - name: Build
        run: plz build ./...

      - name: Test
        run: plz test ./...

  artifacts:
    name: Artifacts
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=readonly

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Compile Go stdlib for Darwin
        run: go install -v std
        env:
          GOOS: darwin

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Please
        uses: sagikazarmark/setup-please-action@v0
        with:
          save-logs: 'true'

      - name: Build
        run: plz build :artifacts

      - name: Upload linux artifact
        uses: actions/upload-artifact@v1
        with:
          name: gogetgen_linux_amd64.tar.gz
          path: plz-out/gen/gogetgen_linux_amd64.tar.gz

      - name: Upload darwin artifact
        uses: actions/upload-artifact@v1
        with:
          name: gogetgen_darwin_amd64.tar.gz
          path: plz-out/gen/gogetgen_darwin_amd64.tar.gz

      - name: Upload checksums
        uses: actions/upload-artifact@v1
        with:
          name: checksums.txt
          path: plz-out/gen/checksums.txt
